"""Model-specific prompts for DeepSeek-R1 and Qwen2.5-Coder

This module provides standardized prompts following official API documentation:
- DeepSeek-R1: api-docs.deepseek.com
- Qwen2.5-Coder: qwen.readthedocs.io
"""

from .deepseek_r1 import (
    DEEPSEEK_R1_SYSTEM_PROMPT,
    DEEPSEEK_R1_RCA_PROMPT,
    DEEPSEEK_R1_LOOP_ANALYSIS_PROMPT,
    DEEPSEEK_R1_STATE_DESIGN_PROMPT,
    DEEPSEEK_R1_CONFIG,
)

from .qwen_coder import (
    QWEN_CODER_SYSTEM_PROMPT,
    QWEN_CODER_IMPLEMENTATION_PROMPT,
    QWEN_CODER_REFACTORING_PROMPT,
    QWEN_CODER_PACKAGE_CREATION_PROMPT,
    QWEN_CODER_DEBUG_FIX_PROMPT,
    QWEN_CODER_CONFIG,
    QWEN_CODER_TOOLS,
    QWEN_CODER_QUALITY_RULES,
)

__all__ = [
    "DEEPSEEK_R1_SYSTEM_PROMPT",
    "DEEPSEEK_R1_RCA_PROMPT",
    "DEEPSEEK_R1_LOOP_ANALYSIS_PROMPT",
    "DEEPSEEK_R1_STATE_DESIGN_PROMPT",
    "DEEPSEEK_R1_CONFIG",
    "QWEN_CODER_SYSTEM_PROMPT",
    "QWEN_CODER_IMPLEMENTATION_PROMPT",
    "QWEN_CODER_REFACTORING_PROMPT",
    "QWEN_CODER_PACKAGE_CREATION_PROMPT",
    "QWEN_CODER_DEBUG_FIX_PROMPT",
    "QWEN_CODER_CONFIG",
    "QWEN_CODER_TOOLS",
    "QWEN_CODER_QUALITY_RULES",
]
